services:
  jellyfin:
    image: jellyfin/jellyfin:10
    container_name: jellyfin
    user: ${PUID}:${PGID}
    network_mode: host
    volumes:
      - ${HOST_CONFIG_PATH}:/config
      - ${HOST_CACHE_PATH}:/cache
      - /media/wd/Filme:/media/Filme
      - /media/wd/Musik:/media/Musik
      - /media/wd/Serien:/media/Serien
    restart: unless-stopped
    environment:
      - JELLYFIN_PublishedServerUrl=http://datenschleuder.local:8096
      - TZ=Europe/Berlin
